# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you set,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

environment:
    url: http://www.defaultUrl.com
    name: defaultName

