# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

spring:
    profiles:
        active: dev

environment:
    url: http://www.devUrl.com
    name: devName